### ISSUE TITLE
Nether failed to load shaders, overworld is fine

### ISSUE THREAD

**Issue by NothingMatters1001** [Null-MC/Shrimple#116]
terrain_translucent.vsh: terrain_translucent.vsh: 0(440) : error C1503: undefined variable "GetVoxelBlockPosition"
0(441) : error C1503: undefined variable "GetVoxelGridCell"
0(442) : error C1503: undefined variable "GetVoxelGridCellIndex"
0(443) : error C1503: undefined variable "IsTraceEmptyBlock"
0(443) : error C1503: undefined variable "SetVoxelBlockMask"
0(447) : error C1503: undefined variable "SetVoxelLightMask"

**Comment by NothingMatters1001** [comment]
[23:35:12] [Render thread/INFO]: Reloading pipeline on dimension change: minecraft:overworld => minecraft:the_nether
[23:35:12] [Render thread/INFO]: Destroying pipeline minecraft:overworld
[23:35:12] [Render thread/INFO]: Creating pipeline for dimension minecraft:the_nether
[23:35:12] [Render thread/INFO]: [System] [CHAT] The shaderpack failed to load! Please report the error to the shader developer. Copy Info
[23:35:12] [Render thread/WARN]: Found 7 stored buffers with a total size of 134336520, forcing them to be deleted.
[23:35:12] [Render thread/ERROR]: Failed to create shader rendering pipeline, disabling shaders!
net.irisshaders.iris.gl.shader.ShaderCompileException: terrain_translucent.vsh: terrain_translucent.vsh: 0(440) : error C1503: undefined variable "GetVoxelBlockPosition"
0(441) : error C1503: undefined variable "GetVoxelGridCell"
0(442) : error C1503: undefined variable "GetVoxelGridCellIndex"
0(443) : error C1503: undefined variable "IsTraceEmptyBlock"
0(443) : error C1503: undefined variable "SetVoxelBlockMask"
0(447) : error C1503: undefined variable "SetVoxelLightMask"

	at knot/net.minecraft.class_281.handler$ccj000$iris$causeException(class_281.java:536) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_281.method_34416(class_281.java:68) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_281.method_1283(class_281.java:51) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_5944.method_34579(class_5944.java:210) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_5944.<init>(class_5944.java:157) ~[client-intermediary.jar:?]
	at knot/net.irisshaders.iris.pipeline.programs.ExtendedShader.<init>(ExtendedShader.java:80) ~[iris-fabric-1.8.1+mc1.21.1.jar:?]
	at knot/net.irisshaders.iris.pipeline.programs.ShaderCreator.create(ShaderCreator.java:133) ~[iris-fabric-1.8.1+mc1.21.1.jar:?]
	at knot/net.irisshaders.iris.pipeline.IrisRenderingPipeline.createShader(IrisRenderingPipeline.java:663) ~[iris-fabric-1.8.1+mc1.21.1.jar:?]
	at knot/net.irisshaders.iris.pipeline.IrisRenderingPipeline.createShader(IrisRenderingPipeline.java:640) ~[iris-fabric-1.8.1+mc1.21.1.jar:?]
	at knot/net.irisshaders.iris.pipeline.IrisRenderingPipeline.lambda$new$7(IrisRenderingPipeline.java:398) ~[iris-fabric-1.8.1+mc1.21.1.jar:?]
	at knot/net.irisshaders.iris.pipeline.programs.ShaderMap.<init>(ShaderMap.java:21) ~[iris-fabric-1.8.1+mc1.21.1.jar:?]
	at knot/net.irisshaders.iris.pipeline.IrisRenderingPipeline.<init>(IrisRenderingPipeline.java:389) ~[iris-fabric-1.8.1+mc1.21.1.jar:?]
	at knot/net.irisshaders.iris.Iris.createPipeline(Iris.java:616) ~[iris-fabric-1.8.1+mc1.21.1.jar:?]
	at knot/net.irisshaders.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:33) ~[iris-fabric-1.8.1+mc1.21.1.jar:?]
	at knot/net.minecraft.class_310.handler$ccf000$iris$resetPipeline(class_310.java:12702) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_18097(class_310.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1481(class_310.java:2204) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_634.method_11117(class_634.java:1130) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2724.method_11782(class_2724.java:44) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2724.method_11054(class_2724.java:9) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2600.method_11072(class_2600.java:27) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:162) [client-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:136) [client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_5383(class_1255.java:121) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]

**Comment by NothingMatters1001** [comment]
Have realised it is to do with RTX not working in nether specifically

**Comment by superSecretSigmaAccount** [comment]
Same here
